monitor.alsa.rules = [
  {
    matches = [ { node.name = "~alsa_output.platform-sound.*" } ]
    actions = { update-props = {
      session.suspend-timeout-seconds = 0
      audio.channels = 2
      audio.position = [ FL FR ]
    } }
  }
  {
    matches = [ { node.name = "~alsa_input.platform-sound.*" } ]
    actions = { update-props = { session.suspend-timeout-seconds = 0 } }
  }
]
