monitor.alsa.rules = [
  {
    matches = [ { alsa.card_name = "GLYMUR-A16" } { device.name = "alsa_card.platform-sound" } ]
    actions = { update-props = { api.alsa.use-acp = false } }
  }
  {
    matches = [ { node.name = "~alsa_output.platform-sound.*" } ]
    actions = { update-props = {
      session.suspend-timeout-seconds = 0
      audio.channels = 4
      audio.position = [ FL FR RL RR ]
      channelmix.upmix = true
      channelmix.upmix-method = psd
      channelmix.lfe-cutoff = 0
      channelmix.fc-cutoff = 12000
      channelmix.rear-delay = 0.0
    } }
  }
  {
    matches = [ { node.name = "~alsa_input.platform-sound.*" } ]
    actions = { update-props = { session.suspend-timeout-seconds = 0 } }
  }
]
