SectionVerb {
	EnableSequence [
		cset "name='WSA_CODEC_DMA_RX_0 Audio Mixer MultiMedia2' 1"
		cset "name='MultiMedia4 Mixer VA_CODEC_DMA_TX_0' 1"
	]
	DisableSequence [
		cset "name='WSA_CODEC_DMA_RX_0 Audio Mixer MultiMedia2' 0"
		cset "name='MultiMedia4 Mixer VA_CODEC_DMA_TX_0' 0"
	]
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker playback"

	EnableSequence [
		# FE-BE Routing
		cset "name='WSA_CODEC_DMA_RX_0 Audio Mixer MultiMedia2' 1"

		# WSA Macro
		cset "name='WSA WSA RX0 MUX' AIF1_PB"
		cset "name='WSA WSA RX1 MUX' AIF1_PB"
		cset "name='WSA WSA_RX0 INP0' RX0"
		cset "name='WSA WSA_RX1 INP0' RX1"
		cset "name='WSA WSA_COMP1 Switch' 1"
		cset "name='WSA WSA_COMP2 Switch' 1"
		cset "name='WSA WSA_RX0 Digital Volume' 81"
		cset "name='WSA WSA_RX1 Digital Volume' 77"

		# WSA2 Macro
		cset "name='WSA2 WSA RX0 MUX' AIF1_PB"
		cset "name='WSA2 WSA RX1 MUX' AIF1_PB"
		cset "name='WSA2 WSA_RX0 INP0' RX0"
		cset "name='WSA2 WSA_RX1 INP0' RX1"
		cset "name='WSA2 WSA_COMP1 Switch' 1"
		cset "name='WSA2 WSA_COMP2 Switch' 1"
		cset "name='WSA2 WSA_RX0 Digital Volume' 81"
		cset "name='WSA2 WSA_RX1 Digital Volume' 77"

		# WSA8845 Four Speakers (WooferLeft, TweeterLeft, WooferRight, TweeterRight)
		cset "name='WooferLeft COMP Switch' 1"
		cset "name='WooferLeft BOOST Switch' 1"
		cset "name='WooferLeft DAC Switch' 1"
		cset "name='WooferLeft PBR Switch' 1"
		cset "name='WooferLeft VISENSE Switch' 0"
		cset "name='WooferLeft WSA MODE' 0"
		cset "name='WooferLeft PA Volume' 6"

		cset "name='TweeterLeft COMP Switch' 1"
		cset "name='TweeterLeft BOOST Switch' 1"
		cset "name='TweeterLeft DAC Switch' 1"
		cset "name='TweeterLeft PBR Switch' 1"
		cset "name='TweeterLeft VISENSE Switch' 0"
		cset "name='TweeterLeft WSA MODE' 0"
		cset "name='TweeterLeft PA Volume' 6"

		cset "name='WooferRight COMP Switch' 1"
		cset "name='WooferRight BOOST Switch' 1"
		cset "name='WooferRight DAC Switch' 1"
		cset "name='WooferRight PBR Switch' 1"
		cset "name='WooferRight VISENSE Switch' 0"
		cset "name='WooferRight WSA MODE' 0"
		cset "name='WooferRight PA Volume' 6"

		cset "name='TweeterRight COMP Switch' 1"
		cset "name='TweeterRight BOOST Switch' 1"
		cset "name='TweeterRight DAC Switch' 1"
		cset "name='TweeterRight PBR Switch' 1"
		cset "name='TweeterRight VISENSE Switch' 0"
		cset "name='TweeterRight WSA MODE' 0"
		cset "name='TweeterRight PA Volume' 6"
	]

	DisableSequence [
		cset "name='WSA_CODEC_DMA_RX_0 Audio Mixer MultiMedia2' 0"
		cset "name='WooferLeft COMP Switch' 0"
		cset "name='WooferLeft BOOST Switch' 0"
		cset "name='WooferLeft DAC Switch' 0"
		cset "name='WooferLeft PBR Switch' 0"
		cset "name='TweeterLeft COMP Switch' 0"
		cset "name='TweeterLeft BOOST Switch' 0"
		cset "name='TweeterLeft DAC Switch' 0"
		cset "name='TweeterLeft PBR Switch' 0"
		cset "name='WooferRight COMP Switch' 0"
		cset "name='WooferRight BOOST Switch' 0"
		cset "name='WooferRight DAC Switch' 0"
		cset "name='WooferRight PBR Switch' 0"
		cset "name='TweeterRight COMP Switch' 0"
		cset "name='TweeterRight BOOST Switch' 0"
		cset "name='TweeterRight DAC Switch' 0"
		cset "name='TweeterRight PBR Switch' 0"
	]

	Value {
		PlaybackChannels 4
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},1"
	}
}

SectionDevice."Mic" {
	Comment "Internal microphones"

	EnableSequence [
		cset "name='MultiMedia4 Mixer VA_CODEC_DMA_TX_0' 1"
		cset "name='VA DEC0 MUX' VA_DMIC"
		cset "name='VA DMIC MUX0' DMIC0"
		cset "name='VA_AIF1_CAP Mixer DEC0' 1"
		cset "name='VA_DEC0 Volume' 100"
		cset "name='VA DEC1 MUX' VA_DMIC"
		cset "name='VA DMIC MUX1' DMIC1"
		cset "name='VA_AIF1_CAP Mixer DEC1' 1"
		cset "name='VA_DEC1 Volume' 100"
	]

	DisableSequence [
		cset "name='MultiMedia4 Mixer VA_CODEC_DMA_TX_0' 0"
	]

	Value {
		CaptureChannels 2
		CapturePriority 100
		CapturePCM "hw:${CardId},3"
	}
}
